import {
  BookOpen,
  Brush,
  Code2,
  Cpu,
  Database,
  Drama,
  FolderGit2,
  Gamepad2,
  GitBranch,
  GraduationCap,
  Landmark,
  Mic,
  type LucideIcon,
  Microchip,
  MonitorPlay,
  Music,
  Network,
  Palette,
  Shapes,
  Sparkles,
  Users,
} from 'lucide-react'

export const 卡片图标表: Record<string, LucideIcon> = {
  degree: GraduationCap,
  coding: Code2,
  systems: Network,
  lowlevel: Database,
  teaching: Users,
  assembly: Cpu,
  arch: Microchip,
  marx: Landmark,
  resumeTheater: Drama,
  xrmUi: Palette,
  aiToolchain: Sparkles,
  toolbox: Shapes,
  generative: Brush,
  novel: BookOpen,
  comedy: Mic,
  gameWorld: Gamepad2,
  courses: MonitorPlay,
  escape: Music,
  yanglai: Gamepad2,
  repoLoop: FolderGit2,
  repoLove: GitBranch,
  repoData: Database,
}
